# Example Site settings

google_analytics: UA-174216737-1

header_pages:
  - headers/index.md
  - headers/about.md
  - headers/art.md
  - headers/translations.md
  - headers/writing.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

style: dark # dark (default) or light
listen_for_clients_preferred_style: false # true or false (default)

plugins:
  - jekyll-seo-tag
